# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation region_graph_root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

from recommonmark.transform import AutoStructify

import libspn_keras


sys.path.insert(0, os.path.abspath(".."))


# -- Project information -----------------------------------------------------

project = "LibSPN Keras"
copyright = "2020, Jos van de Wolfshaar, Andrzej Pronobis"
author = "Jos van de Wolfshaar, Andrzej Pronobis"


# The short X.Y version.
version = libspn_keras.__version__
# The full version, including alpha/beta/rc tags
release = libspn_keras.__version__


language = None

# sys.path.append(os.path.abspath('sphinxext'))


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.coverage",
    "sphinx.ext.napoleon",
    "recommonmark",
    "sphinx_autodoc_typehints",
    "sphinx.ext.autosectionlabel",
]

# Prefix document path to section labels, otherwise autogenerated labels would look like 'heading'
# rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["requirements.txt", "_build"]

defaut_role = None

html_static_path = ["_static"]

pygments_style = "sphinx"

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"


htmlhelp_basename = "LibSPNKerasDoc"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ["_static"]

autodoc_mock_imports = [
    "tensorflow",
    "plotly",
    "tensorflow_probability",
    "colorlover",
    "numpy",
]

github_doc_root = "https://github.com/pronobis/libspn-keras/tree/master/docs"

# The master toctree document.
master_doc = "index"


def setup(app):
    app.add_config_value(
        "recommonmark_config",
        {
            # 'url_resolver': lambda url: github_doc_root + url,
            "auto_toc_tree_section": "Contents",
            "enable_math": False,
            "enable_inline_math": False,
            "enable_eval_rst": True,
        },
        True,
    )
    app.add_transform(AutoStructify)


# html_theme = 'bootstrap'
# html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
#
# html_theme_options = {
#     'bootswatch_theme': "darkly",
#     'bootstrap_version': "3",
# }
